# config.yaml

# Paths
trained_model_path: /home/bingyu/YBY/PROJECT/MATCH/250714/den_cross_fwq/checkpoint_model_epoch_10_0.6996509413769908_0.8615192919969559_0.9274933633018048.pt
sequence_root: demo_seqs/
out_path: output/

# Input
input_size: [384, 384]
batch_size: 1

# Feature Matching Parameters
pre_trained: false
rrange: 20
cross_check_distance: 5.0

# SIFT Parameters
max_feature_detection: 10000
octave_layers: 8
contrast_threshold: 5e-5
edge_threshold: 100
sigma: 1.1

# Device
device_ids: [0]
