# ===============  device  ===============
device_ids: [0]

# ===============  data  ===============
adjacent_range: [1, 20]
network_downsampling: 64
netinput_size: [384, 384]
id_range: [1, 2, 3]
batch_size: 2          # 应该是 16
num_workers: 1         # 应该是 4
num_pre_workers: 1     # 应该是 4
inlier_percentage: 0.99
reprojection_error_threshold: 5
sampling_size: 10
visibility_overlap: 20
heatmap_sigma: 5.0
mask_border_removal: 4

# ===============  training  ===============
lr: 5.0e-6
validation_interval: 10
display_interval: 20
rr_weight: 1.0
training_patient_id: 1
testing_patient_id: 3
validation_patient_id: 2
num_iter: null
display_architecture: true
load_intermediate_data: true
phase: "train_synthetic"   # train_real / train_synthetic
num_epoch: 10              # 下面会覆盖：train_real 时自动变 30
feature_length: 256
filter_growth_rate: 10
matching_scale: 20.0
matching_threshold: 0.9
cross_check_distance: 5.0
ds_temperature: 0.01
corse_confidence_ratio: 0.5

# ===============  model  ===============
load_trained_model: false
trained_model_path: null   # 手动填写或命令行传入

# ===============  path  ===============
log_root: "log"
training_data_root: "EndoMix6"